apiVersion: v1
kind: ConfigMap
metadata:
  name: codespace-rbac-cm
data:
  model.conf: |
    [request_definition]
    r = sub, obj, act, dom

    [policy_definition]
    p = sub, obj, act, dom, eft

    [role_definition]
    g = _, _

    [policy_effect]
    e = some(where (p.eft == allow)) && !some(where (p.eft == deny))

    [matchers]
    m = (g(r.sub, p.sub) || r.sub == p.sub) && (r.obj == p.obj || p.obj == "*") && (r.act == p.act || p.act == "*" || regexMatch(r.act, p.act)) && (p.dom == "*" || r.dom == p.dom || keyMatch(r.dom, p.dom))

  policy.csv: |
    # Role inheritance - Map external OIDC roles to internal roles
    g, codespace-operator:admin, admin
    g, codespace-operator:editor, editor  
    g, codespace-operator:viewer, viewer

    # Example for a single targeted user from an IdP
    # IssuerID derived from: https://idp.example.com/abcd/efgh
    # -> idp.example.com~abcd~efgh
    # p, oidc:idp.example.com~abcd~efgh:8f9a2c...., session, *, team-alpha, allow

    # Admin permissions (full access everywhere)
    p, admin, *, *, *, allow

    # p, admin, session, *, *, allow
    p, admin, namespaces, *, *, allow

    # Editor permissions (CRUD sessions)
    p, editor, session, get, *, allow
    p, editor, session, list, *, allow
    p, editor, session, watch, *, allow
    p, editor, session, create, *, allow
    p, editor, session, update, *, allow
    p, editor, session, delete, *, allow
    p, editor, session, scale, *, allow

    # Viewer permissions (read-only)
    p, viewer, session, get, *, allow
    p, viewer, session, list, *, allow  
    p, viewer, session, watch, *, allow

    # Specific user permissions (examples)
    p, local:admin, *, *, *, allow
    p, local:admin, namespaces, *, *, allow
    p, local:alice, session, *, *, allow
    p, local:bob, session, *, default, allow

    # Environment-specific restrictions (examples)
    p, developer, session, get, dev-*, allow
    p, developer, session, list, dev-*, allow
    p, developer, session, create, dev-*, allow
    p, developer, session, update, dev-*, allow
    p, developer, session, delete, dev-*, deny

    # Deny policies override allows
    p, editor, session, delete, prod-*, deny