{{- if .Values.operator.ingressClass.enabled }}
apiVersion: networking.k8s.io/v1
kind: IngressClass
metadata:
  name: {{ .Values.operator.ingressClass.name }}
spec:
  controller: {{ .Values.operator.ingressClass.controller }}
{{- end }}
