{{- if and .Values.operator.enabled .Values.operator.metrics.enabled .Values.operator.metrics.serviceMonitor.enabled }}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ include "codespace.operator.name" . }}
  namespace: {{ .Values.operator.metrics.serviceMonitor.namespace | default .Release.Namespace }}
  labels:
    {{- $baseLabels := include "codespace.operator.labels" . | fromYaml }}
    {{- $monitorLabels := .Values.operator.metrics.serviceMonitor.labels | default dict }}
    {{- $allLabels := merge (dict) $baseLabels $monitorLabels }}
    {{- toYaml $allLabels | nindent 4 }}
  {{- $annotations := include "codespace.operator.annotations" . }}
  {{- if $annotations }}
  annotations:
    {{- $annotations | nindent 4 }}
  {{- end }}
spec:
  endpoints:
    - port: metrics
      interval: {{ .Values.operator.metrics.serviceMonitor.interval }}
      scrapeTimeout: {{ .Values.operator.metrics.serviceMonitor.scrapeTimeout }}
      scheme: {{ ternary "https" "http" .Values.operator.metrics.secure }}
      {{- if .Values.operator.metrics.secure }}
      tlsConfig:
        insecureSkipVerify: true
      {{- end }}
  selector:
    matchLabels:
      {{- include "codespace.selectorLabels" (dict "name" (include "codespace.name" .) "root" .) | nindent 6 }}
{{- end }}
