{{- if and .Values.operator.enabled .Values.operator.serviceAccount.create }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "codespace.serviceAccountName" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "codespace.operator.labels" . | nindent 4 }}
  {{- $annotations := include "codespace.operator.annotations" . }}
  {{- if $annotations }}
  annotations:
    {{- $annotations | nindent 4 }}
  {{- end }}
automountServiceAccountToken: true
{{- end }}
