{{- if .Values.operator.ingressClass.enabled }}
apiVersion: networking.k8s.io/v1
kind: IngressClass
metadata:
  name: {{ .Values.operator.ingressClass.name }}
  labels:
    {{- include "codespace.operator.labels" . | nindent 4 }}
  {{- $annotations := include "codespace.operator.annotations" . }}
  {{- if $annotations }}
  annotations:
    {{- $annotations | nindent 4 }}
  {{- end }}
spec:
  controller: {{ .Values.operator.ingressClass.controller }}
{{- end }}