{{- if and .Values.server.enabled (hasKey .Values.server "route") .Values.server.route.enabled }}
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: {{ include "codespace.server.name" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "codespace.server.labels" . | nindent 4 }}
  annotations:
    {{- $baseAnnotations := include "codespace.server.annotations" . | fromYaml }}
    {{- $routeAnnotations := .Values.server.route.annotations | default dict }}
    {{- $allAnnotations := merge (dict) $baseAnnotations $routeAnnotations }}
    {{- if $allAnnotations }}
    {{- toYaml $allAnnotations | nindent 4 }}
    {{- end }}
spec:
  to:
    kind: Service
    name: {{ include "codespace.server.serviceName" . }}
  {{- if .Values.server.route.tls }}
  tls:
    {{- toYaml .Values.server.route.tls | nindent 4 }}
  {{- end }}
{{- end }}