{{- if and .Values.server.enabled .Values.server.ingress.enabled }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "codespace.server.name" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "codespace.server.labels" . | nindent 4 }}
  annotations:
    {{- $baseAnnotations := include "codespace.server.annotations" . | fromYaml }}
    {{- $ingressAnnotations := .Values.server.ingress.annotations | default dict }}
    {{- $allAnnotations := merge (dict) $baseAnnotations $ingressAnnotations }}
    {{- if $allAnnotations }}
    {{- toYaml $allAnnotations | nindent 4 }}
    {{- end }}
spec:
  {{- if .Values.server.ingress.className }}
  ingressClassName: {{ .Values.server.ingress.className }}
  {{- end }}
  rules:
  {{- range .Values.server.ingress.hosts }}
    - host: {{ .host }}
      http:
        paths:
          - path: {{ .path | default "/" }}
            pathType: Prefix
            backend:
              service:
                name: {{ include "codespace.server.serviceName" $ }}
                port:
                  number: {{ $.Values.server.service.port }}
  {{- end }}
  {{- with .Values.server.ingress.tls }}
  tls:
    {{- toYaml . | nindent 4 }}
  {{- end }}
{{- end }}