{{- if and .Values.server.enabled .Values.server.networkPolicy.enabled }}
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ include "codespace.server.name" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "codespace.server.labels" . | nindent 4 }}
  {{- $annotations := include "codespace.server.annotations" . }}
  {{- if $annotations }}
  annotations:
    {{- $annotations | nindent 4 }}
  {{- end }}
spec:
  podSelector:
    matchLabels:
      {{- include "codespace.selectorLabels" (dict "name" (printf "%s-server" (include "codespace.name" .)) "root" .) | nindent 6 }}
  policyTypes: ["Ingress","Egress"]
  ingress:
  {{- if .Values.server.networkPolicy.allowIngressFromSameNamespace }}
    - from:
        - podSelector: {}   # allow same-namespace traffic (ingress controller/clients)
    - {}  # Allow all ingress for now to debug
  {{- else }}
    - {}
  {{- end }}
  egress:
    # Allow DNS resolution
    - to: []
      ports:
        - protocol: UDP
          port: 53
        - protocol: TCP
          port: 53
    # Allow Kubernetes API access
    {{- if .Values.server.networkPolicy.egressToKubeAPIServer }}
    - to: []
      ports:
        - protocol: TCP
          port: 443
        - protocol: TCP
          port: 6443
    {{- end }}
    # Allow all egress for debugging
    - to: []
{{- end }}

---