{{- if and .Values.server.enabled .Values.server.auth.enableLocalLogin }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "codespace.server.name" . }}-local-users
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "codespace.server.labels" . | nindent 4 }}
  {{- $annotations := include "codespace.server.annotations" . }}
  {{- if $annotations }}
  annotations:
    {{- $annotations | nindent 4 }}
    # Exclude from kubectl diff to avoid showing password hashes
    helm.sh/resource-policy: keep
  {{- else }}
  annotations:
    # Exclude from kubectl diff to avoid showing password hashes
    helm.sh/resource-policy: keep
  {{- end }}
type: Opaque
data:
  local-users.yaml: {{ .Values.server.localUsers | toYaml | b64enc }}
{{- end }}