nameOverride: ""
fullnameOverride: ""
podLabels: {}
podAnnotations: {}

operator:
  enabled: true
  podLabels: {}
    # component: operator
    # tier: control-plane

  podAnnotations: {}
    # operator-specific annotations
  rbac:
    create: true

  image:
    repository: ghcr.io/codespace-operator/codespace-operator
    tag: "{{chart.AppVersion}}"
    pullPolicy: IfNotPresent

  replicaCount: 1

  serviceAccount:
    create: true
    name: ""

  webhook:
    enabled: false
    certPath: ""
    certName: tls.crt
    certKey: tls.key

  metrics:
    name: ""
    enabled: true
    secure: true
    bindAddress: :8443
    service:
      type: ClusterIP
      annotations: {}
      port: 8443
      targetPort: 443
    serviceMonitor:
      enabled: false
      namespace: ""
      interval: 30s
      scrapeTimeout: 10s
      labels: {}


  enableHTTP2: false

  resources:
    limits: {}
    requests:
      cpu: 100m
      memory: 128Mi

  nodeSelector: {}
  tolerations: []
  affinity: {}

  extraArgs: []


  securityContext: {}
  containerSecurityContext:
    allowPrivilegeEscalation: false
    readOnlyRootFilesystem: true
    runAsNonRoot: true

  ingressClass:
    enabled: false
    name: codespace-operator
    controller: k8s.io/ingress-controller/codespace-operator

server:
  enabled: true
  podLabels: {}
  podAnnotations: {}

  clusterScope: false

  oidc:
    insecureSkipVerify: false
    issuer: "" # e.g. https://dev-123456.okta.com
    clientID: ""
    clientSecret: ""
    redirectURL: "" # e.g. https://your.host/auth/callback
    scopes: [openid, profile, email]

  allowTokenParam: false
  session:
    ttlMinutes: 60
    cookieName: ""  # optional override

  route:
    enabled: false
    annotations: {}
    tls:
      termination: edge

  logLevel: info
  enableLocalLogin: true

  auth:
    # IMPORTANT: set a stable secret in prod; chart generates one if empty
    jwtSecret: "" # set for stable upgrades
    bootstrapUser: admin # single local admin
    bootstrapPassword: admin # chart generates random if empty
  image:
    repository: ghcr.io/codespace-operator/codespace-server
    tag: "{{chart.AppVersion}}"
    pullPolicy: IfNotPresent

  env:
    # Same-origin by default; set to http://localhost:5173 only for local dev
    allowOrigin: "*"
  service:
    type: ClusterIP
    annotations: {}
    name: "" # auto generate otherwise
    port: 8443
    targetPort: 8443 # container's port

  ingress:
    enabled: false
    className: ""
    annotations: {}
    hosts:
      - host: console.codespace.test
        path: /
    tls: []

  probes:
    readinessPath: /readyz
    livenessPath: /healthz

  resources:
    requests:
      cpu: 50m
      memory: 64Mi
    limits:
      cpu: 500m
      memory: 256Mi

  securityContext:
    runAsUser: 1001
    runAsNonRoot: true
    fsGroup: 2000
    seccompProfile:
      type: RuntimeDefault

  containerSecurityContext:
    allowPrivilegeEscalation: false
    readOnlyRootFilesystem: true
    runAsNonRoot: true
    capabilities:
      drop: [ALL]

  nodeSelector: {}
  tolerations: []
  affinity: {}
  useManagerServiceAccount: false

  serviceAccount:
    create: true
    name: ""

  rbac:
    create: true

  networkPolicy:
    enabled: true
    allowIngressFromSameNamespace: true
    egressToKubeAPIServer: true

  # Password is a hash using openssl passwd -6 "string"
  configs:
    localUsers: |
      # SHA-512 hash with salt: openssl passwd -6 "yourpass"
      users:
        - username: admin
          passwordHash: "$$6$hDZOMQRBnH3gk5fU$5krq9XTy.rbkLNUUEmggUbYulK/Dp1.Y3gvn/pavqYGlyvB4qhPFmeFyOVEyOnnFowo8WW5tItiT0M1wChGtO."
          email: admin@local.com
