{{- if .Values.server.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "codespace.server.name" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "codespace.server.labels" . | nindent 4 }}
  {{- $annotations := include "codespace.server.annotations" . }}
  {{- if $annotations }}
  annotations:
    {{- $annotations | nindent 4 }}
  {{- end }}
spec:
  replicas: 1
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 0
      maxSurge: 1
  selector:
    matchLabels:
      {{- include "codespace.selectorLabels" (dict "name" (printf "%s-server" (include "codespace.name" .)) "root" .) | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "codespace.server.podLabels" . | nindent 8 }}
      annotations:
        # Force restart on config changes
        checksum/rbac: {{ include (print $.Template.BasePath "/server-configmap-rbac.yaml") . | sha256sum }}
        checksum/secret: {{ include (print $.Template.BasePath "/server-secret.yaml") . | sha256sum }}
        {{- if .Values.server.auth.providers.local.enabled }}
        checksum/users: {{ include (print $.Template.BasePath "/server-users-secret.yaml") . | sha256sum }}
        {{- end }}
        {{- $podAnnotations := include "codespace.server.podAnnotations" . }}
        {{- if $podAnnotations }}
        {{- $podAnnotations | nindent 8 }}
        {{- end }}
    spec:
      serviceAccountName: {{ if .Values.server.useManagerServiceAccount }}{{ include "codespace.serviceAccountName" . }}{{ else }}{{ include "codespace.server.serviceAccountName" . }}{{ end }}
      {{- with .Values.server.securityContext }}
      securityContext:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      containers:
        - name: server
          image: "{{ .Values.server.image.repository }}:{{ .Values.server.image.tag }}"
          imagePullPolicy: {{ .Values.server.image.pullPolicy }}
          ports:
            - name: http
              containerPort: {{ .Values.server.service.targetPort }}
              protocol: TCP
          env:
            # ================= CORE =================
            - name: CODESPACE_SERVER_CLUSTER_SCOPE
              value: {{ .Values.server.clusterScope | quote }}
            - name: CODESPACE_SERVER_PORT
              value: {{ .Values.server.service.targetPort | quote }}
            - name: CODESPACE_SERVER_LOG_LEVEL
              value: {{ .Values.server.logLevel | quote }}
            - name: CODESPACE_SERVER_ALLOW_ORIGIN
              value: {{ .Values.server.env.allowOrigin | quote }}

            # ================ MANAGER (manager.*) ================
            - name: CODESPACE_SERVER_MANAGER_JWT_SECRET
              valueFrom:
                secretKeyRef:
                  name: {{ include "codespace.server.name" . }}-auth
                  key: jwt-secret

            - name: CODESPACE_SERVER_MANAGER_SESSION_TTL
              value: {{ .Values.server.auth.manager.sessionTTL | quote }}

            {{- if .Values.server.auth.manager.cookieName }}
            - name: CODESPACE_SERVER_MANAGER_SESSION_COOKIE_NAME
              value: {{ .Values.server.auth.manager.cookieName | quote }}
            {{- end }}

            - name: CODESPACE_SERVER_MANAGER_ALLOW_TOKEN_PARAM
              value: {{ .Values.server.auth.manager.allowTokenParam | quote }}

            - name: CODESPACE_SERVER_MANAGER_AUTH_PATH
              value: {{ .Values.server.auth.manager.authPath | default "/auth" | quote }}
            - name: CODESPACE_SERVER_MANAGER_AUTH_LOGOUT_PATH
              value: {{ .Values.server.auth.manager.authLogoutPath | default "/auth/logout" | quote }}

            - name: CODESPACE_SERVER_MANAGER_SAME_SITE
              value: {{ .Values.server.auth.manager.sameSite | default "Lax" | quote }}
            - name: CODESPACE_SERVER_MANAGER_ABSOLUTE_SESSION_MAX
              value: {{ .Values.server.auth.manager.absoluteMax | default "24h" | quote }}

            # ================ LOCAL (providers.local.*) ==========
            - name: CODESPACE_SERVER_PROVIDERS_LOCAL_ENABLED
              value: {{ .Values.server.auth.providers.local.enabled | quote }}

            {{- if .Values.server.auth.providers.local.enabled }}
            - name: CODESPACE_SERVER_PROVIDERS_LOCAL_USERS_PATH
              value: /etc/codespace-operator/local-users.yaml
            {{- end }}

            {{- if .Values.server.auth.providers.local.bootstrapLoginAllowed }}
            - name: CODESPACE_SERVER_PROVIDERS_LOCAL_BOOTSTRAP_ALLOWED
              value: "true"
            - name: CODESPACE_SERVER_PROVIDERS_LOCAL_BOOTSTRAP_USER
              valueFrom:
                secretKeyRef:
                  name: {{ include "codespace.server.name" . }}-auth
                  key: bootstrap-user
            - name: CODESPACE_SERVER_PROVIDERS_LOCAL_BOOTSTRAP_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ include "codespace.server.name" . }}-auth
                  key: bootstrap-password
            {{- else }}
            - name: CODESPACE_SERVER_PROVIDERS_LOCAL_BOOTSTRAP_ALLOWED
              value: "false"
            {{- end }}

            # ================== OIDC (providers.oidc.*) ==================
            {{- if .Values.server.auth.providers.oidc.enabled }}
            - name: CODESPACE_SERVER_PROVIDERS_OIDC_ENABLED
              value: "true"
            - name: CODESPACE_SERVER_PROVIDERS_OIDC_ISSUER_URL
              value: {{ .Values.server.auth.providers.oidc.issuerURL | quote }}
            - name: CODESPACE_SERVER_PROVIDERS_OIDC_CLIENT_ID
              value: {{ .Values.server.auth.providers.oidc.clientID | quote }}
            - name: CODESPACE_SERVER_PROVIDERS_OIDC_CLIENT_SECRET
              valueFrom:
                secretKeyRef:
                  name: {{ include "codespace.server.name" . }}-auth
                  key: oidc-client-secret
            - name: CODESPACE_SERVER_PROVIDERS_OIDC_REDIRECT_URL
              value: {{ .Values.server.auth.providers.oidc.redirectURL | quote }}
            - name: CODESPACE_SERVER_PROVIDERS_OIDC_INSECURE_SKIP_VERIFY
              value: {{ .Values.server.auth.providers.oidc.insecureSkipVerify | quote }}

            # Scopes: viper usually parses CSV to []string. Keep CSV here.
            - name: CODESPACE_SERVER_PROVIDERS_OIDC_SCOPES
              value: {{ join "," .Values.server.auth.providers.oidc.scopes | quote }}
            {{- end }}

            # ================== LDAP (providers.ldap.*) ==================
            {{- if .Values.server.auth.providers.ldap.enabled }}
            - name: CODESPACE_SERVER_PROVIDERS_LDAP_ENABLED
              value: {{ .Values.server.auth.providers.ldap.enabled | quote }}
            - name: CODESPACE_SERVER_PROVIDERS_LDAP_URL
              value: {{ .Values.server.auth.providers.ldap.url | quote }}
            - name: CODESPACE_SERVER_PROVIDERS_LDAP_START_TLS
              value: {{ .Values.server.auth.providers.ldap.startTLS | quote }}
            - name: CODESPACE_SERVER_PROVIDERS_LDAP_INSECURE_SKIP_VERIFY
              value: {{ .Values.server.auth.providers.ldap.insecureSkipVerify | quote }}

            - name: CODESPACE_SERVER_PROVIDERS_LDAP_BIND_DN
              value: {{ .Values.server.auth.providers.ldap.bindDN | quote }}
            {{- if ne .Values.server.auth.providers.ldap.bindPassword "" }}
            - name: CODESPACE_SERVER_PROVIDERS_LDAP_BIND_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ include "codespace.server.name" . }}-auth
                  key: ldap-bind-password
            {{- end }}

            # User resolution
            {{- if .Values.server.auth.providers.ldap.userDNTemplate }}
            - name: CODESPACE_SERVER_PROVIDERS_LDAP_USER_DN_TEMPLATE
              value: {{ .Values.server.auth.providers.ldap.userDNTemplate | quote }}
            {{- end }}
            {{- if .Values.server.auth.providers.ldap.userBaseDN }}
            - name: CODESPACE_SERVER_PROVIDERS_LDAP_USER_BASE_DN
              value: {{ .Values.server.auth.providers.ldap.userBaseDN | quote }}
            {{- end }}
            {{- if .Values.server.auth.providers.ldap.userFilter }}
            - name: CODESPACE_SERVER_PROVIDERS_LDAP_USER_FILTER
              value: {{ .Values.server.auth.providers.ldap.userFilter | quote }}
            {{- end }}
            {{- if .Values.server.auth.providers.ldap.usernameAttr }}
            - name: CODESPACE_SERVER_PROVIDERS_LDAP_USERNAME_ATTR
              value: {{ .Values.server.auth.providers.ldap.usernameAttr | quote }}
            {{- end }}
            {{- if .Values.server.auth.providers.ldap.emailAttr }}
            - name: CODESPACE_SERVER_PROVIDERS_LDAP_EMAIL_ATTR
              value: {{ .Values.server.auth.providers.ldap.emailAttr | quote }}
            {{- end }}
            {{- if .Values.server.auth.providers.ldap.displayNameAttr }}
            - name: CODESPACE_SERVER_PROVIDERS_LDAP_DISPLAY_NAME_ATTR
              value: {{ .Values.server.auth.providers.ldap.displayNameAttr | quote }}
            {{- end }}
            - name: CODESPACE_SERVER_PROVIDERS_LDAP_TO_LOWER_USERNAME
              value: {{ .Values.server.auth.providers.ldap.toLowerUsername | quote }}

            # Group / roles
            {{- if .Values.server.auth.providers.ldap.groupBaseDN }}
            - name: CODESPACE_SERVER_PROVIDERS_LDAP_GROUP_BASE_DN
              value: {{ .Values.server.auth.providers.ldap.groupBaseDN | quote }}
            {{- end }}
            {{- if .Values.server.auth.providers.ldap.groupFilter }}
            - name: CODESPACE_SERVER_PROVIDERS_LDAP_GROUP_FILTER
              value: {{ .Values.server.auth.providers.ldap.groupFilter | quote }}
            {{- end }}
            {{- if .Values.server.auth.providers.ldap.groupAttr }}
            - name: CODESPACE_SERVER_PROVIDERS_LDAP_GROUP_ATTR
              value: {{ .Values.server.auth.providers.ldap.groupAttr | quote }}
            {{- end }}

            {{- if .Values.server.auth.providers.ldap.roleMapping }}
            - name: CODESPACE_SERVER_PROVIDERS_LDAP_ROLE_MAPPING
              value: {{ toJson .Values.server.auth.providers.ldap.roleMapping | quote }}
            {{- end }}
            {{- if .Values.server.auth.providers.ldap.defaultRoles }}
            - name: CODESPACE_SERVER_PROVIDERS_LDAP_DEFAULT_ROLES
              value: {{ join "," .Values.server.auth.providers.ldap.defaultRoles | quote }}
            {{- end }}
            {{- end }}

            # ================= RBAC paths ================
            - name: CODESPACE_SERVER_RBAC_MODEL_PATH
              value: /etc/codespace-operator/rbac/model.conf
            - name: CODESPACE_SERVER_RBAC_POLICY_PATH
              value: /etc/codespace-operator/rbac/policy.csv

            {{- if .Values.server.auth.providers.local.enabled }}
            - name: CODESPACE_SERVER_PROVIDERS_LOCAL_USERS_PATH
              value: /etc/codespace-operator/local-users.yaml
            {{- end }}

            # ============ Downward API ============
            - name: POD_NAME
              valueFrom: { fieldRef: { fieldPath: metadata.name } }
            - name: POD_UID
              valueFrom: { fieldRef: { fieldPath: metadata.uid } }
            - name: POD_NAMESPACE
              valueFrom: { fieldRef: { fieldPath: metadata.namespace } }
            - name: POD_IP
              valueFrom: { fieldRef: { fieldPath: status.podIP } }
            - name: NODE_NAME
              valueFrom: { fieldRef: { fieldPath: spec.nodeName } }


          volumeMounts:
            # RBAC configuration files
            - name: rbac-config
              mountPath: /etc/codespace-operator/rbac
              readOnly: true
            # Local users configuration (if enabled)
            {{- if .Values.server.auth.providers.local.enabled }}
            - name: local-users
              mountPath: /etc/codespace-operator/local-users.yaml
              subPath: local-users.yaml
              readOnly: true
            {{- end }}

          # Health checks
          readinessProbe:
            httpGet:
              path: {{ .Values.server.probes.readinessPath }}
              port: {{ .Values.server.service.targetPort }}
              scheme: HTTP
            initialDelaySeconds: 10
            periodSeconds: 10
            timeoutSeconds: 5
            failureThreshold: 3
            successThreshold: 1

          livenessProbe:
            httpGet:
              path: {{ .Values.server.probes.livenessPath }}
              port: {{ .Values.server.service.targetPort }}
              scheme: HTTP
            initialDelaySeconds: 30
            periodSeconds: 30
            timeoutSeconds: 10
            failureThreshold: 3
            successThreshold: 1

          {{- with .Values.server.resources }}
          resources:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          
          {{- with .Values.server.containerSecurityContext }}
          securityContext:
            {{- toYaml . | nindent 12 }}
          {{- end }}

      # Volume definitions
      volumes:
        - name: rbac-config
          configMap:
            name: {{ include "codespace.server.rbac.configMapName" . }}
            defaultMode: 0644
        {{- if .Values.server.auth.providers.local.enabled }}
        - name: local-users
          secret:
            secretName: {{ include "codespace.server.name" . }}-local-users
            defaultMode: 0600
        {{- end }}

      # Scheduling
      {{- with .Values.server.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.server.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.server.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
{{- end }}