{{- if .Values.server.enabled }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "codespace.server.rbac.configMapName" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "codespace.server.labels" . | nindent 4 }}
  {{- $annotations := include "codespace.server.annotations" . }}
  {{- if $annotations }}
  annotations:
    {{- $annotations | nindent 4 }}
  {{- end }}
data:
  model.conf: |
    {{- .Values.server.rbac.model | nindent 4 }}
  policy.csv: |
    {{- .Values.server.rbac.policy | nindent 4 }}
{{- end }}